### ISSUE TITLE
Error runing demo instances

### ISSUE THREAD

**Issue by eikebartels** [Solid-Interactive/grasshopper-core-nodejs#65] opened 2015-05-10 08:24 UTC
Any idea? 

```
Projects/test [ node app] 4:05 pm
/Users/eikebartels/Documents/Projects/test/node_modules/grasshopper-api/node_modules/body-parser/node_modules/bytes/index.js:13
    , n = parseFloat(parts[1])
                          ^
TypeError: Cannot read property '1' of null
    at module.exports (/Users/eikebartels/Documents/Projects/test/node_modules/grasshopper-api/node_modules/body-parser/node_modules/bytes/index.js:13:27)
    at Function.json (/Users/eikebartels/Documents/Projects/test/node_modules/grasshopper-api/node_modules/body-parser/lib/types/json.js:49:7)
    at module.exports (/Users/eikebartels/Documents/Projects/test/node_modules/grasshopper-api/lib/grasshopper-api.js:59:20)
    at Object.<anonymous> (/Users/eikebartels/Documents/Projects/test/app/lib/grasshopper.js:4:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by pajtai** [comment] 2015-05-10 16:28
can you give a bit of context? how did you set the project up (gh jump or fly) and which endpoint are you hitting.... or does the error show up on startup?

**Comment by eikebartels** [comment] 2015-05-11 03:30
I made sure that every dependency is installed (nodejs, grunt-cli, bower, sass-globbing, sass-css-importer, mongodb) and then I used the command > grasshopper fly 
to install grasshopper

**Comment by travism** [comment] 2015-05-12 23:08
I reproduced this error, I think there is a simple config change that can be made. I will reply back with an update.

**Comment by travism** [comment] 2015-05-12 23:14
It looks like the bodyparser module was expecting a different value (old one in bytes).

Try changing the bodyparser limit in `grasshopper-config.json` to be `5mb` instead of `5000000` and run `node app`

That worked for me. We will change the value in our config and close the issue.

**Comment by travism** [comment] 2015-05-12 23:27
Ok we published a fix for it. If you run `npm update -g grasshopper-cli` and then `grasshopper fly` in your project directory it should work for you now.

**Closed by travism** 2015-05-12 23:27 UTC

**Comment by eikebartels** [comment] 2015-05-13 08:59
Yes works! Thanks for the fix!
